package com.dshbox.app.bridge.security

import android.net.Uri
import com.dshbox.app.common.Constants

/**
 * Verifies the origin of a page that tries to use the JS bridge.
 *
 * Trust model:
 * - [TrustLevel.PUBLIC_WEB]: any internet page, or a malformed/unrecognized
 *   URL. No bridge access at all.
 * - [TrustLevel.LOCAL_WEB]: a loopback page (127.0.0.1 / localhost / ::1).
 *   Local web-access only; never granted bridge capabilities on its own,
 *   because any local app could otherwise open such a page.
 * - [TrustLevel.TRUSTED_DSH_WEBUI]: only granted by [isTrustedDshWebUi] when
 *   ALL of the following hold:
 *     1. The page is served from a loopback address.
 *     2. The port is the runtime DSH WebUI port ([Constants.dshPort], 3080
 *        by default and overridable via Intent extras).
 *     3. The JS bridge handshake presents the capability token that matches
 *        the one generated by the app (see BridgeRouter).
 */
object OriginVerifier {

    /** Loopback hosts treated as "local". */
    private val ALLOWED_LOCAL_HOSTS = setOf("127.0.0.1", "localhost", "::1")

    /** Only these schemes can ever be local/trusted. */
    private val ALLOWED_SCHEMES = setOf("http", "https")

    /** Parses [url] into a structured [WebOrigin]; null when the URL is unusable. */
    fun parse(url: String): WebOrigin? {
        val uri = Uri.parse(url) ?: return null
        val scheme = uri.scheme?.lowercase() ?: return null
        val host = uri.host?.lowercase() ?: return null
        val port = uri.port
        return WebOrigin(
            url = url,
            scheme = scheme,
            host = host,
            port = if (port in 1..65535) port else null,
        )
    }

    fun classify(url: String): TrustLevel {
        val origin = parse(url) ?: return TrustLevel.PUBLIC_WEB
        if (origin.scheme !in ALLOWED_SCHEMES) return TrustLevel.PUBLIC_WEB
        if (origin.host !in ALLOWED_LOCAL_HOSTS) return TrustLevel.PUBLIC_WEB
        return TrustLevel.LOCAL_WEB
    }

    /**
     * DSH WebUI is only treated as trusted when all checks pass: loopback
     * origin, DSH default port, capability token match against [expectedToken].
     *
     * The port check is important: a malicious local page (e.g. served on
     * port 9999) must not gain bridge access even if it somehow knows the
     * token, because the token is only ever injected into the real DSH page.
     */
    fun isTrustedDshWebUi(
        url: String,
        capabilityToken: String?,
        expectedToken: String?,
    ): Boolean {
        val origin = parse(url) ?: return false
        if (origin.scheme !in ALLOWED_SCHEMES) return false
        if (origin.host !in ALLOWED_LOCAL_HOSTS) return false
        // The DSH WebUI always includes its port. Compare against the runtime
        // port (Constants.dshPort), which may differ from the compile-time
        // default when overridden via Intent extras. A URL without an explicit
        // port means a different local service — do not trust it.
        if (origin.port != Constants.dshPort) return false
        if (capabilityToken.isNullOrBlank()) return false
        return capabilityToken == expectedToken
    }
}